version: "3.8"

services:
  app:
    build: .
    container_name: icecream-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=ice-cream
      - JWT_SECRET=2rD@qF1vX8h!pR9mK6yZ$wT5aL^bJ3s
      - JWT_EXPIRES_USER=1h
      - JWT_EXPIRES_MANAGER=6h
      - JWT_EXPIRES_SUPER_ADMIN=12h
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: icecream-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: